//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 03:08:32 PM CET 
//


package de.esri.osm.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="osm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="arcgis" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "field")
public class Field {

    @XmlAttribute(name = "osm")
    protected String osm;
    @XmlAttribute(name = "arcgis")
    protected String arcgis;

    /**
     * Gets the value of the osm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsm() {
        return osm;
    }

    /**
     * Sets the value of the osm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsm(String value) {
        this.osm = value;
    }

    /**
     * Gets the value of the arcgis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArcgis() {
        return arcgis;
    }

    /**
     * Sets the value of the arcgis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArcgis(String value) {
        this.arcgis = value;
    }

}
