//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 03:08:32 PM CET 
//


package de.esri.osm.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}matching"/>
 *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="osmurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="osmid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "matching",
    "data",
    "osmurl",
    "osmid"
})
@XmlRootElement(name = "fields")
public class Fields {

    @XmlElement(required = true)
    protected Matching matching;
    @XmlElement(required = true)
    protected String data;
    @XmlElement(required = true)
    protected String osmurl;
    @XmlElement(required = true)
    protected String osmid;

    /**
     * Gets the value of the matching property.
     * 
     * @return
     *     possible object is
     *     {@link Matching }
     *     
     */
    public Matching getMatching() {
        return matching;
    }

    /**
     * Sets the value of the matching property.
     * 
     * @param value
     *     allowed object is
     *     {@link Matching }
     *     
     */
    public void setMatching(Matching value) {
        this.matching = value;
    }
    
    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
	 * Sets the value of the data property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setData(String value) {
	    this.data = value;
	}
	
	/**
     * Gets the value of the osmurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsmurl() {
        return osmurl;
    }

    /**
	 * Sets the value of the osmurl property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setOsmurl(String value) {
	    this.osmurl = value;
	}

	/**
     * Gets the value of the osmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsmid() {
        return osmid;
    }

    /**
	 * Sets the value of the osmid property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setOsmid(String value) {
	    this.osmid = value;
	}
}
