//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 10:53:52 AM CEST 
//


package de.esri.osm.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.esri.osm.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.esri.osm.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Configuration.Query }
     * 
     */
    public Configuration.Query createConfigurationQuery() {
        return new Configuration.Query();
    }

    /**
     * Create an instance of {@link Configuration.Query.Matching }
     * 
     */
    public Configuration.Query.Matching createConfigurationQueryMatching() {
        return new Configuration.Query.Matching();
    }

    /**
     * Create an instance of {@link Configuration.Query.Matching.Fields }
     * 
     */
    public Configuration.Query.Matching.Fields createConfigurationQueryMatchingFields() {
        return new Configuration.Query.Matching.Fields();
    }

    /**
     * Create an instance of {@link Configuration.Query.Arcgis }
     * 
     */
    public Configuration.Query.Arcgis createConfigurationQueryArcgis() {
        return new Configuration.Query.Arcgis();
    }

    /**
     * Create an instance of {@link Configuration.Query.Overpass }
     * 
     */
    public Configuration.Query.Overpass createConfigurationQueryOverpass() {
        return new Configuration.Query.Overpass();
    }

    /**
     * Create an instance of {@link Configuration.Query.Matching.Fields.Field }
     * 
     */
    public Configuration.Query.Matching.Fields.Field createConfigurationQueryMatchingFieldsField() {
        return new Configuration.Query.Matching.Fields.Field();
    }

    /**
     * Create an instance of {@link Configuration.Query.Arcgis.Login }
     * 
     */
    public Configuration.Query.Arcgis.Login createConfigurationQueryArcgisLogin() {
        return new Configuration.Query.Arcgis.Login();
    }

}
