//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 11:25:54 AM CET 
//


package de.esri.geotrigger.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}arcgis"/>
 *         &lt;element ref="{}trigger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "arcgis",
    "trigger"
})
@XmlRootElement(name = "query")
public class Query {

    @XmlElement(required = true)
    protected Arcgis arcgis;
    @XmlElement(required = true)
    protected Trigger trigger;

    /**
     * Gets the value of the arcgis property.
     * 
     * @return
     *     possible object is
     *     {@link Arcgis }
     *     
     */
    public Arcgis getArcgis() {
        return arcgis;
    }

    /**
     * Sets the value of the arcgis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Arcgis }
     *     
     */
    public void setArcgis(Arcgis value) {
        this.arcgis = value;
    }

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link Trigger }
     *     
     */
    public Trigger getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trigger }
     *     
     */
    public void setTrigger(Trigger value) {
        this.trigger = value;
    }

}
